repository: Cyberiums/cyberium

theme: minima

keep_files:
  - static

favicon: /static/images/favicon.png

defaults:
  - scope:
      path: ""
    values:
      layout: sidebar
  - scope:
      path: "*"
    values:
      root: "../.."
  - scope:
      path: "*/*"
    values:
      root: "../.."

default_root: "../.."

collections_dir: docs
collections:
  getting-started:
    output: true
    caption: Getting Started
    sidebar_index: 1
    frontpage: _getting-started/index.md
  signup-and-start:
    output: true
    permalink: docs/:collection/:slug
    caption: Signup and Build
    sidebar_index: 2
    frontpage: _signup-and-start/signup-studio-account.md
  interface:
    output: true
    permalink: docs/:collection/:slug
    caption: Using Geth Flavours
    sidebar_index: 3
  interface2:
    output: true
    permalink: docs/:collection/:slug
    caption: Using Fabric Flavours
    sidebar_index: 4
  app:
    output: true
    permalink: docs/:collection/:slug
    caption: For App Developers
    frontpage: _app/native.md
    sidebar_index: 5
  public:
    output: true
    permalink: docs/:collection/:slug
    caption: JSON RPC APIs
    frontpage: _public/server.md
    sidebar_index: 6
  developers:
    output: true
    permalink: docs/:collection/:slug
    caption: For Geth Flavours Developers
    frontpage: _developers/devguide.md
    sidebar_index: 7
  clef:
    output: true
    permalink: docs/:collection/:slug
    caption: Clef
    sidebar_index: 8
    frontpage: _clef/Tutorial.md
  whisper:
    output: true
    permalink: docs/:collection/:slug
    caption: Whisper
    sidebar_index: 9
    frontpage: _whisper/Whisper-Overview.md
