repository: Cyberiums/cyberium

theme: minima

keep_files:
  - static

favicon: /static/images/favicon.png

defaults:
  - scope:
      path: ""
    values:
      layout: sidebar
  - scope:
      path: "*"
    values:
      root: "../.."
  - scope:
      path: "*/*"
    values:
      root: "../.."

default_root: "../.."

collections_dir: docs
collections:
  getting-started:
    output: true
    caption: Getting Started
    sidebar_index: 1
    frontpage: _getting-started/index.md
  signup-and-start:
    output: true
    permalink: docs/:collection/:slug
    caption: Signup and Build
    sidebar_index: 2
    frontpage: _signup-and-start/signup-studio-account.md
  interface:
    output: true
    permalink: docs/:collection/:slug
    caption: Using Geth Flavours
    sidebar_index: 3
  interface2:
    output: true
    permalink: docs/:collection/:slug
    caption: Using Fabric Flavours
    sidebar_index: 4
  app:
    output: true
    permalink: docs/:collection/:slug
    caption: For App Developers
    frontpage: _app/native.md
    sidebar_index: 5
  public:
    output: true
    permalink: docs/:collection/:slug
    caption: Hosting Public App
    frontpage: _public/server.md
    sidebar_index: 6
  wallet:
    output: true
    permalink: docs/:collection/:slug
    caption: Wallets
    frontpage: _wallet/devguide.md
    sidebar_index: 7
  bandwidth:
    output: true
    permalink: docs/:collection/:slug
    caption: Creating Ultra High Bandwidth
    sidebar_index: 8
    frontpage: _bandwidth/Tutorial.md
  partners:
    output: true
    permalink: docs/:collection/:slug
    caption: Building Exchange & Partnerships
    sidebar_index: 9
    frontpage: _partners/Whisper-Overview.md
  org:
    output: true
    permalink: docs/:collection/:slug
    caption: Setup Organization
    sidebar_index: 10
    frontpage: _org/Organization-Overview.md
