repository: Cyberiums/cyberium

theme: minima

keep_files:
  - static

favicon: /static/images/favicon.png

defaults:
  - scope:
      path: ""
    values:
      layout: sidebar
  - scope:
      path: "*"
    values:
      root: "../.."
  - scope:
      path: "*/*"
    values:
      root: "../.."

default_root: "../.."

collections_dir: docs
collections:
  getting-started:
    output: true
    caption: Getting Started
    sidebar_index: 1
    frontpage: _getting-started/index.md
  signup-and-start:
    output: true
    permalink: docs/:collection/:slug
    caption: Signup and Build Frontend
    sidebar_index: 2
    frontpage: _signup-and-start/signup-studio-account.md
  org:
    output: true
    permalink: docs/:collection/:slug
    caption: Setup Organization
    sidebar_index: 3
    frontpage: _org/Organization-Overview.md
  interface:
    output: true
    permalink: docs/:collection/:slug
    caption: Geth Blockchain Flavours
    sidebar_index: 4
  bandwidth:
    output: true
    permalink: docs/:collection/:slug
    caption: Creating Ultra High Bandwidth
    sidebar_index: 6
    frontpage: _bandwidth/Tutorial.md
  wallet:
    output: true
    permalink: docs/:collection/:slug
    caption: Wallets
    frontpage: _wallet/genguide.md
    sidebar_index: 9
  partners:
    output: true
    permalink: docs/:collection/:slug
    caption: Building Exchange & Partnerships
    sidebar_index: 10
    frontpage: _partners/Partner-Overview.md
